# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - Project-TAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # Better to align with what Azure supports (e.g. 8.2 or 8.3)
          php-version: '8.4'
          extensions: mbstring, intl, pdo_mysql, bcmath, openssl, tokenizer

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Install dependencies (composer)
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          composer validate --no-check-publish
          composer install --prefer-dist --no-progress --no-dev
          composer dump-autoload --optimize

      # Optional: run Laravel optimizations on the artifact
      - name: Laravel optimizations
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          php artisan config:clear || true
          php artisan config:cache || true
          php artisan route:cache || true
          php artisan view:cache || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read  #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_067A9F3CC7084918A5518511FF00C5E9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C60D61AD966E49409B1C56A3A0BFD2AF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_40E501E15F1F4711BEA1086859128EB3 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Project-TAPI'
          slot-name: 'Production'
          package: .
